name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Clippy (Linter)
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test

      - name: Run Code Coverage with Tarpaulin
        run: cargo tarpaulin --fail-under 100 --exclude-files src/main.rs src/entropy.rs
